Add tiling example
nasa/dorado-scheduling pull request #5
Opened 2021-03-11 20:42 UTC by mcoughlin

Quick example to make a tiling on the sphere

2021-03-11 20:59 UTC, lpsinger requested changes
Nice, but we'll have to move this to a module eventually.

2021-03-11 20:59 UTC, lpsinger commented on README.md
> +        $ dorado-scheduling-animate examples/6.fits examples/6.ecsv examples/6.gif
Good catch! I just fixed that on master, so please rebase.

2021-03-11 20:59 UTC, lpsinger commented on dorado/scheduling/scripts/tile.py
> +    FOV = FOV_size*FOV_size*scale
Please fix these lint errors.

2021-03-11 20:59 UTC, lpsinger commented on dorado/scheduling/scripts/tile.py
> +    print("Using %d points to tile the sphere..."%n)
Suggest removing print statement.

2021-03-11 20:59 UTC, lpsinger commented on dorado/scheduling/scripts/tile.py
> +    return ra, dec
```suggestion
    coords = SkyCoord(radius, theta * u.rad, z, representation_type='cylindrical')
    coords.representation_type = 'unitspherical'
    return coords
```

2021-03-11 20:59 UTC, lpsinger commented on dorado/scheduling/scripts/tile.py
> +import logging
```suggestion
```

Remove unused import.

2021-03-11 20:59 UTC, lpsinger commented on dorado/scheduling/scripts/tile.py
> +import healpy as hp
```suggestion
from astropy.coordinates import SkyCoord
```

2021-03-11 21:00 UTC, lpsinger commented
Would you mind plotting the output of this please, to check?

2021-03-12 04:52 UTC, lpsinger commented
Here's what this looks like near the north celestial pole. It has a lot of overlap. Does this look correct?

![image_2021_03_12T01_05_54_932Z](https://user-images.githubusercontent.com/728407/110893822-bd88eb80-82c4-11eb-96d5-6bcfc583e0fc.png)

2021-03-12 12:11 UTC, mcoughlin commented
Yeah I just added one that I think behaves a bit better at the poles. Can we add that script to tiles.py for the plotting?

2021-03-12 13:50 UTC, lpsinger commented
What is the provenance of these algorithms? Have they been used for previous surveys?

2021-03-12 13:55 UTC, mcoughlin commented
I have used a variation on these to produce tilings for various telescopes, including DECam and others. I usually tune the overlaps by hand a bit for the various surveys to get some reasonable amount of overlap, which also means needing to play around a bit close to the poles.

2021-03-12 14:18 UTC, lpsinger commented
Would you please add docstrings with references to the journal articles where these grids are introduced, described, or used?

2021-03-12 14:21 UTC, lpsinger commented on dorado/scheduling/scripts/tile.py
> +def tesselation_packing(FOV_size, scale=0.97):
This is a pretty generic name.

2021-03-12 15:08 UTC, lpsinger commented
I'm ready to merge this as soon as legal processes your CLA. So sorry about the red tape.

2021-03-12 21:17 UTC, lpsinger commented
I added geodesic grids: https://dorado-scheduling.readthedocs.io/en/latest/reference/tesselation.html

2021-03-12 21:17 UTC, mcoughlin commented
awesome leo!

2021-03-16 20:53 UTC, lpsinger commented
They finally got your CLA processed. I'd like to see this unified with the new `dorado.scheduling.tesselation` module, but since I added that after you had opened this PR, I could merge this as is and do the refactoring myself. What would you prefer?

2021-03-16 21:02 UTC, mcoughlin commented
Let's get this merged and then I can help as necessary this weekend when I have more time. Thanks Leo.

2021-03-16 21:03 UTC, merged